MCU = RP2040
BOOTLOADER = rp2040

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
VIAL_INSECURE = yes

WS2812_DRIVER = vendor
OLED_ENABLE = yes
OLED_DRIVER = ssd1306